title: Emacs.el
full_title:  Emacs.el Podcast
description: > # this means to ignore newlines until "baseurl:"
  Emacs.el, the podcast where we talk about Emacs and nothing but Emacs!
  We talk about packages, cool configs, and people who make all of this
  possible.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emacsel.com"
twitter_username: emacsel
github_username:  emacsel

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

livereload: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
